#!/bin/bash

if ! command -v python3 >/dev/null 2>&1; then
    echo "Please install python"
    exit 1
fi

if ! command -v pip >/dev/null 2>&1; then
    echo "Please install pip"
    exit 2
fi

echo 'hey'
pip install playsound
python3 sound.py
